exclude: 'doc/conf.py'

repos:

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.3
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==23.1]
    - id: nbqa-isort
      additional_dependencies: [isort==5.11.5]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.254'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      
      
