exclude: 'doc/conf.py'

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        # for now don't force to change from %-operator to {}
        args: [--keep-percent-format, --py38-plus]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
        args: [--remove]

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

-   repo: https://github.com/PyCQA/isort/
    rev: 5.10.1
    hooks:
    -   id: isort

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.2.3
  hooks:
    - id: nbqa-black
      additional_dependencies: [black==20.8b1]
    - id: nbqa-isort
      additional_dependencies: [isort==5.7.0]

-   repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
    -   id: yesqa
