language: python
matrix:
  include:
  - name: Python 3.7
    python: 3.7
    sudo: true
    dist: bionic
    env: QT_QPA_PLATFORM=offscreen
    services:
    - xvfb

install:
    - pip install coveralls mypy
    - pip install --upgrade pip
    - pip install PyQt5
    - pip install git+https://git@github.com/QuTech-Delft/qtt.git@ace939d9821357e877268bc9939ef94b70bb839f
    - pip install -e .
    - pip install jupyter
    - export QT_QPA_PLATFORM=offscreen

script:
    - ls
    - pytest --version
    - xvfb-run -a coverage run --source="./quantumdataset" -m pytest
    - mypy quantumdataset --ignore-missing-imports
    - jupyter nbconvert --to notebook --execute "docs/example_quantum_dataset.ipynb"

after_success:
  - coveralls
