language: python
matrix:
  include:
  - name: Python 3.7
    python: 3.7
    sudo: true
    dist: xenial
    env: QT_QPA_PLATFORM=offscreen
    services:
    - xvfb

install:
    - pip install coveralls mypy
    - pip install -e .
    - export QT_QPA_PLATFORM=offscreen

script:
    - ls
    - pytest --version
    - xvfb-run -a coverage run --source="./quantumdataset" -m pytest
    - mypy quantumdataset --ignore-missing-imports
    - jupyter nbconvert --to notebook --execute "docs/example_quantum_dataset.ipynb"

after_success:
  - coveralls
