language: python
matrix:
  include:
  - name: Python 3.10
    python: "3.10"
    sudo: true
    dist: focal
    env: QT_QPA_PLATFORM=offscreen
    services:
    - xvfb

install:
    - pip install --upgrade pip
    - pip install qtt jupyter coveralls mypy
    - pip install -e .
    - export QT_QPA_PLATFORM=offscreen

script:
    - ls
    - pytest --version
    - xvfb-run -a coverage run --source="./quantumdataset" -m pytest
    - xvfb-run -a jupyter nbconvert --to notebook --execute "docs/example_quantum_dataset.ipynb"

after_success:
  - coveralls
